"""One durable local worker per UPLOAD_DIR. Start separately with python -m app.worker."""
import logging
import time
from datetime import timedelta

from filelock import FileLock, Timeout
from sqlalchemy import select, update

from app.core.config import Settings
from app.db.session import create_database
from app.models.entities import AnalysisJob, utcnow
from app.services.inference import detect, report

log = logging.getLogger("scoutai.worker")


def remove_upload(settings, job):
    # Paths are generated by the server; guard the boundary again for maintenance operations.
    root = settings.upload_dir.resolve()
    path = (root / job.stored_filename).resolve()
    if path.parent == root:
        path.unlink(missing_ok=True)


def recover(sessions, settings):
    with sessions() as db:
        interrupted = db.scalars(select(AnalysisJob).where(AnalysisJob.status == "processing",
                                                          AnalysisJob.stage != "awaiting_selection"))
        for job in interrupted:
            job.status, job.error, job.completed_at = "failed", "Worker interrupted. Upload the video again.", utcnow()
            remove_upload(settings, job)
        db.commit()


def cleanup(sessions, settings):
    cutoff = utcnow() - timedelta(days=settings.job_retention_days)
    with sessions() as db:
        for job in db.scalars(select(AnalysisJob).where(AnalysisJob.created_at < cutoff)):
            if job.status in ("queued", "processing"):
                job.status, job.error, job.completed_at = "failed", "Unfinished job expired; upload again.", utcnow()
            remove_upload(settings, job)
            job.tracks, job.gallery = {}, []
        db.commit()
        referenced = set(db.scalars(select(AnalysisJob.stored_filename)))
    for path in settings.upload_dir.iterdir():
        if path.suffix in (".mp4", ".mov", ".avi") and path.name not in referenced:
            if time.time() - path.stat().st_mtime > 86400:
                path.unlink(missing_ok=True)


def process_next(sessions, settings):
    with sessions() as db:
        job = db.scalar(select(AnalysisJob).where(AnalysisJob.status == "queued")
                        .order_by(AnalysisJob.created_at).limit(1))
        if job is None:
            return False
        changed = db.execute(update(AnalysisJob).where(AnalysisJob.id == job.id, AnalysisJob.status == "queued")
                             .values(status="processing", started_at=job.started_at or utcnow()))
        if changed.rowcount != 1:
            db.rollback()
            return False
        db.commit()
        db.refresh(job)
        try:
            def progress(value):
                with sessions() as progress_db:
                    progress_db.execute(update(AnalysisJob).where(AnalysisJob.id == job.id).values(progress=value))
                    progress_db.commit()
                (settings.upload_dir / ".worker-heartbeat").touch()

            if job.stage == "detection":
                job.tracks, job.gallery = detect(job, settings, progress)
                job.stage, job.progress = "awaiting_selection", 80
            elif job.stage == "reporting":
                progress(90)
                job.result = report(job)
                job.status, job.stage, job.progress = "completed", "done", 100
                job.completed_at = utcnow()
                job.tracks = {}
            else:
                raise ValueError("Unknown processing stage")
        except Exception as error:
            log.exception("Analysis %s failed", job.id)
            job.status, job.stage, job.completed_at = "failed", "done", utcnow()
            job.error = str(error)[:500] if isinstance(error, ValueError) else "CV processing failed. See worker logs using this analysis ID."
            job.tracks = {}
        finally:
            # Detection persists everything needed for selection/reporting. Keep no source videos afterward.
            remove_upload(settings, job)
            db.commit()
    return True


def main():
    logging.basicConfig(level=logging.INFO)
    settings = Settings()
    settings.upload_dir.mkdir(parents=True, exist_ok=True)
    engine, sessions = create_database(settings)
    lock = FileLock(settings.upload_dir / ".worker.lock", timeout=0)
    try:
        with lock:
            recover(sessions, settings)
            cleanup(sessions, settings)
            last_cleanup = time.monotonic()
            log.info("Worker ready (%s)", "DEMO" if settings.demo_mode else "REAL")
            while True:
                (settings.upload_dir / ".worker-heartbeat").touch()
                if not process_next(sessions, settings):
                    time.sleep(1)
                if time.monotonic() - last_cleanup > 3600:
                    cleanup(sessions, settings)
                    last_cleanup = time.monotonic()
    except Timeout:
        raise SystemExit("Another worker owns this upload directory; run only one worker.") from None
    except KeyboardInterrupt:
        pass
    finally:
        engine.dispose()


if __name__ == "__main__":
    main()
